name: 'Docker Build'

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      workingDir:
        required: true
        type: string

jobs:
  docker-build:
    name: 'Docker Build'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workingDir }}
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v5

    -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # OIDC Connection to AWS
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.2.1
      with:
        audience: sts.amazonaws.com
        aws-region: ${{ env.AWS_REGION }}
        role-to-assume: ${{ env.AWS_ROLE_ARN }}
        role-session-name: ${{ env.TF_ROLE_SESSION_NAME }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1